


all:
	pdflatex program
	pdflatex features
	pdflatex chisel-10min
	pdflatex chisel-30min
	pdflatex unit1
	pdflatex unit2
	pdflatex unit3
	pdflatex unit4

clean:
	rm -fr *.aux *.bbl *.blg *.log *.lof *.lot *.toc *.gz *.pdf *.lol
	rm -rf *.nav *.out *.snm *.vrb
