all:
	pdflatex reg_en_wave.tex
	pdflatex reg_wave.tex
	pdflatex rising.tex
	pdflatex tick_wave.tex
	pdflatex uart_wave.tex
	pdflatex ready_valid1.tex
	pdflatex ready_valid2.tex
	pdflatex ready_valid3.tex
	pdflatex tick_count_wave.tex
